Jacques/docker compose docs
comet-ml/opik pull request #246
Opened 2024-09-15 17:40 UTC by jverre

## Details

Updated the Opik documentation with the new self-hosting instructions using the docker-compose approach rather than the Opik installer.

Before this PR is merged, we will need to merge the docker compose PR and the `opik login` PR.

2024-09-15 20:01 UTC, liyaka commented
@jverre please see the changes in my PR for docker-compose - moved to separate folder and added README

2024-09-15 20:42 UTC, jverre commented
Thanks @liyaka, yep once the other PR is merged I'll update the doc

2024-09-16 09:54 UTC, andrescrz requested changes
Please see overlapping changes.

2024-09-16 09:54 UTC, andrescrz commented on docker-compose.yaml
Overlaps: https://github.com/comet-ml/opik/pull/245/files

2024-09-16 09:54 UTC, andrescrz commented on nginx_default_local.conf
Overlaps: https://github.com/comet-ml/opik/pull/245/files

2024-09-16 09:54 UTC, andrescrz commented on sdks/python/src/opik/cli.py
Please double check changes in this file. CC: @alexkuzmik

2024-09-16 19:19 UTC, merged