[OPIK-99] Implement batching for spans creation
comet-ml/opik pull request #298
Opened 2024-09-20 16:00 UTC by alexkuzmik

## Details
Added batching for CREATE-SPAN requests.
Batches are flushed to the streamer queue automatically every second or whenever accumulated message items reach max batch size limit (at the moment - 1000 items).

## Issues

Resolves the issue when SDK sends a lot of CREATE-SPAN requests to the backend independetly, loading it and utilizing more network resources. 
Backend should be less loaded, 

## Testing
Added unit tests. E2E tests also pass, but this PR requires extra QA. 

## Documentation
-

2024-09-23 13:28 UTC, andrescrz reviewed
One comment, but mostly LGTM. I had maybe some comment about optimising the batcher lock, but I don't want to create additional noise. 

Once this is reviewed and validated, from my side we're good to go.

2024-09-23 13:28 UTC, andrescrz commented on sdks/python/src/opik/message_processing/batching/base_batcher.py
> +        flush_interval: float,
You need to make clear the time unit of the flush internal. After that, probably makes sense to use an integer type and go with milliseconds.

2024-09-24 14:30 UTC, japdubengsub approved these changes

2024-09-24 16:14 UTC, thiagohora submitted a review, later dismissed

2024-09-25 08:02 UTC, andrescrz requested changes
As discussed, let's debug why span `name` is none with this change before proceeding with the merge.

2024-09-25 10:54 UTC, andrescrz reviewed
Just a few more comments while the discussed items are implemented.

2024-09-25 10:54 UTC, andrescrz commented on .github/workflows/sdk-e2e-tests.yaml
> +            docker compose up -d --build --force-recreate --no-deps
Let's double check if these flags `--force-recreate --no-deps` were just a temporary fix or if we need it in the long run:

- https://github.com/comet-ml/opik/pull/309

If the later, we need to propagate this everywhere.

2024-09-25 10:54 UTC, andrescrz commented on .github/workflows/sdk-e2e-tests.yaml
> +            export OPIK_CONSOLE_LOGGING_LEVEL=DEBUG
It might be too noisy, better at INFO.

2024-09-25 10:54 UTC, andrescrz commented on deployment/docker-compose/docker-compose.yaml
> +        OPIK_VERSION: ${OPIK_VERSION:-latest}
Same, let's double check if this was temporary.

2024-09-25 10:54 UTC, andrescrz commented on sdks/python/src/opik/message_processing/batching/batch_manager_constuctors.py
> +CREATE_SPANS_MESSAGE_BATCHER_FLUSH_INTERVAL = 1.0
Minor: constant naming missing the time unit. (...IN_SECONDS).

2024-09-25 10:54 UTC, andrescrz commented on sdks/python/src/opik/message_processing/batching/flushing_thread.py
> +        probe_interval: float = 0.1,
Missing time unit: `_in_seconds`.

2024-09-25 14:14 UTC, alexkuzmik commented on .github/workflows/sdk-e2e-tests.yaml
> +            export OPIK_CONSOLE_LOGGING_LEVEL=DEBUG
It's intentional for e2e tests debugging. Now it's not noisy, in case it will - we'll adjust.

2024-09-25 14:15 UTC, alexkuzmik commented on deployment/docker-compose/docker-compose.yaml
> +        OPIK_VERSION: ${OPIK_VERSION:-latest}
@thiagohora ? I thought it's a part of the fix.

2024-09-25 14:17 UTC, alexkuzmik commented on .github/workflows/sdk-e2e-tests.yaml
> +            docker compose up -d --build --force-recreate --no-deps
@thiagohora

2024-09-25 14:49 UTC, thiagohora commented on deployment/docker-compose/docker-compose.yaml
> +        OPIK_VERSION: ${OPIK_VERSION:-latest}
Yeah, shit seems to be missing in our docker image. We such a variable.

2024-09-25 14:49 UTC, thiagohora commented on deployment/docker-compose/docker-compose.yaml
> +        OPIK_VERSION: ${OPIK_VERSION:-latest}
![Screenshot 2024-09-25 at 16 49 55](https://github.com/user-attachments/assets/a70813c9-4109-410f-8583-d249cfec5818)

2024-09-25 14:56 UTC, thiagohora commented on .github/workflows/sdk-e2e-tests.yaml
> +            docker compose up -d --build --force-recreate --no-deps
The is that --build only builds if the tag specified doesn't exist yet. However, all PR seems to run with the value. 

[ARG OPIK_VERSION](https://github.com/comet-ml/opik/blob/main/deployment/docker-compose/docker-compose.yaml#L61)

2024-09-25 14:58 UTC, thiagohora commented on .github/workflows/sdk-e2e-tests.yaml
> +            docker compose up -d --build --force-recreate --no-deps
This forces the rebuid of the image/tag

2024-09-26 07:54 UTC, andrescrz reviewed
Let's just wait on some input from @liyaka for the build fixes. Anything else LGTM.

2024-09-26 07:54 UTC, andrescrz commented on .github/workflows/sdk-e2e-tests.yaml
> +            docker compose up -d --build --force-recreate --no-deps
It will conflict with this PR:
- https://github.com/comet-ml/opik/pull/310
Please @liyaka leave your thoughts here.

2024-09-26 07:54 UTC, andrescrz commented on deployment/docker-compose/docker-compose.yaml
> +        OPIK_VERSION: ${OPIK_VERSION:-latest}
@liyaka please see this thread above.

2024-09-30 14:02 UTC, andrescrz submitted a review, later dismissed
Undone the e2e infra changes as they conflict and they should tackled separately.

2024-09-30 14:16 UTC, Nimrod007 approved these changes

2024-09-30 14:16 UTC, merged