Improve release version update
comet-ml/opik pull request #421
Opened 2024-10-17 19:51 UTC by ferc

## Details
- Add a select to pick which version to increment (major, minor or patch)
- Use `cut` to get the version parts

## Issues

Resolves #

## Testing

## Documentation

2024-10-17 20:01 UTC, liyaka approved these changes

2024-10-21 13:33 UTC, liyaka requested changes

2024-10-21 13:33 UTC, liyaka commented on .github/workflows/release.yaml
> +        id: increment_version
i suggest to add
`shell: bash`

2024-10-21 13:33 UTC, liyaka commented on .github/workflows/release.yaml
> +      - name: Push new version.txt
you don't need this one

2024-10-21 13:33 UTC, liyaka commented on .github/workflows/release.yaml
> +    uses: ./.github/workflows/build_and_publish_sdk.yml
i see the name of the file is build_and_publish_sdk.yaml

2024-10-28 18:06 UTC, ferc commented
I'll reopen it soon

2024-10-28 18:06 UTC, closed without merging