Enable Project Name Specification for running experiment
comet-ml/opik pull request #479
Opened 2024-10-25 07:09 UTC by Jeff-67

## Details
This update allows the evaluate function in the Opik SDK to accept a project_name argument. Previously, the evaluate function defaulted to logging in the "Default project," limiting control over tracing destinations. With the addition of project_name, users can specify the project for logging, facilitating better organization and management of experiment results.

## Issues

Resolves #

## Testing

## Documentation

2024-10-25 11:55 UTC, jverre commented
Thanks for the PR @Jeff-67 !

I've reviewed it and there is an issue with the nested trace data (that appears when you click on the trace icon in the experiment table) not being logged to the right project.

I think there might be an easier way to implement this, if instead of updating the `get_client_cached` function we actually pass the project name down to the `_process_item` method. Then from there you can pass the project name to the `trace.TraceData` method. Then everything should be logged correctly and we avoid changing a method that is used in a few places

Let me know if that makes sense and happy to provide more details on this

2024-10-28 02:39 UTC, Jeff-67 commented
@jverre Thanks for the review and guidance! I have updated the code to pass the project_name down to the _process_item function as you suggested. Let me know if there is anything you'd like me to adjust.

2024-10-28 12:21 UTC, alexkuzmik requested changes

2024-10-28 12:21 UTC, alexkuzmik commented on sdks/python/src/opik/evaluation/evaluator.py
> +        project_name=client._project_name if project_name is None else project_name,
In this particular place you can just pass `project_name=project_name`.
Opik client will use the default string value by itself, if `project_name` is `None` in `TraceData`.

2024-10-28 12:21 UTC, alexkuzmik commented on sdks/python/src/opik/evaluation/tasks_scorer.py
> +    project_name: str,
after updating the code in the `evaluator.py`, it will become `project_name: Optional[str]`

2024-10-28 12:21 UTC, alexkuzmik commented on sdks/python/src/opik/evaluation/tasks_scorer.py
> +    project_name: str,
after updating the code in the `evaluator.py`, it will become `project_name: Optional[str]`

2024-10-29 01:44 UTC, Jeff-67 commented
@alexkuzmik thanks for the comments! The code we updated.

2024-10-29 13:04 UTC, alexkuzmik commented
@Jeff-67 thanks!
Please run `pre-commit run --all-files` from `opik/sdks/python` folder to fix the lint errors and we're ready to merge.
(we will prepare a contribution guide soon and try to make some parts of the process smoother).

2024-10-29 13:54 UTC, merged