Add ARM64 support for Docker images
comet-ml/opik pull request #951
Opened 2024-12-21 10:24 UTC by vishwamartur

Related to #696

Add support for multi-architecture builds for Opik frontend and backend images.

* Update `apps/opik-backend/Dockerfile` and `apps/opik-frontend/Dockerfile` to include `--platform` flag for multi-architecture builds.
* Modify `.github/workflows/build_and_push_docker.yaml` to include `--platform` flag in the `docker build` and `docker push` commands.
* Update `deployment/docker-compose/docker-compose.yaml` and `deployment/docker-compose/docker-compose.override.yaml` to specify `platform: linux/amd64,linux/arm64` for `backend` and `frontend` services.
* Update `deployment/docker-compose/README.md` to include instructions for multi-architecture builds.

Pending task build_apps.yaml
Docker push & build 
Linux support arm AMD

2024-12-21 11:48 UTC, jverre commented
@vishwamartur Thanks for the PR, @liyaka will take a look on Sunday

2024-12-22 11:53 UTC, liyaka commented
Hi @vishwamartur - it's not running on linux - please see one of the failed workflows. It failed with error:
`"amd64,linux" is an invalid component of "linux/amd64,linux/arm64": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument`
we also need it to run on Mac and Windows.
In general you can run it on any platform using `--platform `flag

2024-12-23 13:10 UTC, Nimrod007 requested changes
@vishwamartur thanks for taking the time to submit this pull request. we are working internally to achieve this and will submit a followup PR from our team. im closing this for now and will ping you soon once we open the new PR

2024-12-23 13:10 UTC, Nimrod007 commented on deployment/docker-compose/docker-compose.yaml
> +    platform: linux/amd64,linux/arm64
we will add `platform`  as optional in `docker-compose-override` only if needed 
please remove

2024-12-23 13:10 UTC, Nimrod007 commented on deployment/docker-compose/docker-compose.yaml
> +    platform: linux/amd64,linux/arm64
we will add `platform`  as optional in `docker-compose-override` only if needed 
please remove

2024-12-23 13:10 UTC, Nimrod007 commented on deployment/docker-compose/docker-compose.override.yaml
> +    platform: linux/amd64,linux/arm64
This should be optional, only adding an example in `docker-compose/README.md` file 
please remove

2024-12-23 13:10 UTC, Nimrod007 commented on deployment/docker-compose/docker-compose.override.yaml
> +    platform: linux/amd64,linux/arm64
This should be optional, only adding an example in `docker-compose/README.md` file 
please remove

2024-12-23 13:10 UTC, Nimrod007 commented on deployment/docker-compose/README.md
> +## Multi-Architecture Builds
```suggestion
## Run locally on different architectures (arm/amd)
```

2024-12-23 13:10 UTC, Nimrod007 commented on deployment/docker-compose/README.md
> +To build the Opik frontend and backend images for both `linux/amd64` and `linux/arm64` architectures, you can use the following command:
```suggestion
To run Opik on different architectures add `platform` for each service in [docker-compose-override.yaml](https://github.com/comet-ml/opik/blob/main/deployment/docker-compose/docker-compose.override.yaml)
`platform: linux/amd64`
```

2024-12-23 13:10 UTC, Nimrod007 commented on deployment/docker-compose/README.md
> +```bash
we will override in docker-compose please remove

2024-12-23 13:10 UTC, Nimrod007 commented on apps/opik-frontend/Dockerfile
> +FROM --platform=linux/amd64,linux/arm64 node:20.15.0-alpine3.20 as builder
I dont think multiple platforms are supported here. 
we will add this to the build and push job. please remove

2024-12-23 13:10 UTC, Nimrod007 commented on apps/opik-frontend/Dockerfile
> +FROM --platform=linux/amd64,linux/arm64 nginx:1.27.3-alpine3.20
I dont think multiple platforms are supported here. 
we will add this to the build and push job. please remove

2024-12-23 13:10 UTC, Nimrod007 commented on apps/opik-backend/Dockerfile
> +FROM --platform=linux/amd64,linux/arm64 amazoncorretto:21-al2023
I dont think multiple platforms are supported here. 
we will add this to the build and push job. please remove

2024-12-23 13:10 UTC, Nimrod007 commented on apps/opik-backend/Dockerfile
> +FROM --platform=linux/amd64,linux/arm64 maven:3.9.9-amazoncorretto-21-al2023 AS build
I dont think multiple platforms are supported here. 
we will add this to the build and push job. please remove

2024-12-23 13:10 UTC, closed without merging